# .github/workflows/deploy.yml
name: Deploy to Xserver

on:
  push:
    branches:
      - production  # 'main' から 'production' に変更

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🚀 Sync files to Xserver
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # エックスサーバーの公開ディレクトリを指定します
        server-dir: /tatsumi-gr.jp/public_html/events/darumarche-2026
        # 不要なファイルを転送から除外します
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
